### ISSUE TITLE
Android Crashes with stepCount={1}

### ISSUE THREAD

**Issue by interstates21** [24ark/react-native-step-indicator#88]
![image](https://user-images.githubusercontent.com/28481785/75092500-bc353580-5580-11ea-9cd2-59d0d4555da8.png)

**Comment by SilverInfinity** [comment]
Also encountering this on both iOS and Android.
I have pages of varying lengths, and want to keep a visual consistency by always having the page count, even if there is only one page.

I believe this error is caused by
```js
const animateToPosition = (this.state.progressBarSize/ (stepCount - 1)) * position;
```
in `onCurrentPositionChanged`

When stepCount is 1, then it is dividing by zero, which results in an invalid value for the progressBar width.

No progress bar should be needed if there is only 1 step.

**Comment by rf1804** [comment]
@interstates21 @SilverInfinity waiting for my PR #84 to merge which resolves this issue

**Comment by 24ark** [comment]
Version 1.0.3 should fix this issue: https://github.com/24ark/react-native-step-indicator/blob/1df202c5f819b58445c2b1b99a0e08dc8398f4e0/src/index.tsx#L399
